### ISSUE TITLE
| Žádost o nové funkce, návrhy a chybové hlášení |

### ISSUE THREAD

**Issue by Nexusatko-zz** [TheDevTec/ServerControlReloaded#1]
Zdar,
rád bych nejdříve nahlásil jednu chybovou hlášku, která se vyskytuje při připojení hráče, ale jinak ho normálně pustí.

> Chybová hláška **[ZDE](https://pastebin.com/BFbMxNxJ)**

A teď k žádosti o funkce a nějaké ty návrhy.

| Žádosti a návrhy
> Přidat /scr help, nebo prostě cokoliv, co by hráčům řeklo jaké příkazy se přesně nacházejí a jsou implementované. A pokud by jste se "náhodou" nudili, tak udělat něco jako.. počáteční nastavení jazyka a podle toho by SCR posílal i správy.. možná zložité, ale vím, že to je možné.
> Přidat alias pro /item na /i
> Promyslet a přidat nějaké obsáhlejší návody k SCR, co jak funguje a také ohledně formátováni četu, páč nikdo nespadl z nebe moudrý a nepochopí to jen tak ve většině případu, co znám.
> Bylo by také dobré implementovat tvorbu vlastných Menu ( GUis ) do SCR, a nějaké další funkce. 
> Také, pokud by to bylo možné a byl na to čas, a také nálada, tak by jste mohli udělat něco jako AdminFun sekci SCR, a nebo implementovat AdminFun plugin a nějak implementaci pluginu vylepšit, přidat více možností. :D 

**Tohle je pro dnešek ode mě vše, a doufám, že se podpora tohto pluginu jen, tak neskončí a bude pokračovať.** :)

**Přeji hezký den, DevTec Teame**

**Comment by TheDevTec** [comment]
Error on player join fixed.
